# Generated by Django 3.0.5 on 2020-04-17 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chrisapp', '0002_punchline'),
    ]

    operations = [
        migrations.AddField(
            model_name='joke',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='joke',
            name='punchline_text',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.DeleteModel(
            name='Punchline',
        ),
    ]
